AllCops:
  TargetRubyVersion: 2.4.0
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 24

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
